### ISSUE TITLE
Error on inserting paycheck in functions.php

### ISSUE THREAD

**Issue by MaxCalhoun** [RyanYoak/DDDabases#5]
If you insert a paycheck that has the same date but a different employee id as another paycheck, then you get an error

example error:
Could not insert paycheck, data: Duplicate entry '2019-11-03' for key 'pay_date'

**Comment by MaxCalhoun** [comment]
Pretty sure this has to do with the way the table was initialized

CREATE TABLE if NOT EXISTS payroll (
	employee_id     int,
  pay_date        date NOT NULL UNIQUE,
	paycheck_amount	numeric(9,2) NOT NULL,
	foreign key (employee_id) references employee(employee_id)


pay_date should not be unique, but the combination of employee_id and pay_date should be

**Comment by peterle08** [comment]
add CONSTRAINT unique_paycheck UNIQUE (employee_id, pay_date), to payroll table
